version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - my-network
  server:
    container_name: myapp
    image: my-netpro-app:1.0
    ports: 
      - 8000:8000
    depends_on:
      - mongo
    networks:
      - my-network

networks:
  my-network:
    name: my-network